steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-east1-docker.pkg.dev/braided-gist-388110/intelliscale-busy-server/server-dev:${SHORT_SHA}', '.']
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-east1-docker.pkg.dev/braided-gist-388110/intelliscale-busy-server/server-dev:${SHORT_SHA}']
 